исправлен workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,29 +7,41 @@ jobs:
   migrate:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+    - name: Checkout repository
+      uses: actions/checkout@v2
 
-      - name: Flyway Migration
-        run: |
-          # Загрузка Flyway Command-line
-          wget -qO flyway.tar.gz https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.13/flyway-commandline-8.5.13-linux-x64.tar.gz
-          tar -xzf flyway.tar.gz
-          # Запуск миграций к базе данных "store"
-          ./flyway-8.5.13/flyway -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/store" -user="${{ secrets.DB_USER }}" -password="${{ secrets.DB_PASSWORD }}" migrate
+    #### Добавьте шаг с Flyway-миграциями
+    - name: Install Flyway
+      run: |
+        curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
+        tar -xzf flyway-commandline.tar.gz || { echo "Flyway extraction failed!"; exit 1; }
+        ls -l
+        sudo mv flyway-11.1.0 /usr/local/flyway || { echo "Moving Flyway failed!"; exit 1; }
+        sudo ln -s /usr/local/flyway/flyway /usr/local/bin/flyway || { echo "Symlink creation failed!"; exit 1; }
+        echo "Flyway installation completed!"
 
-      - name: Download and setup autotests binaries
-        run: |
-          wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
-          chmod +x ./dbopstest
-          mv ./dbopstest /usr/local/bin/dbopstest
+    - name: Run Flyway migrations
+      env:
+        FLYWAY_URL: "jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
+        FLYWAY_USER: ${{ secrets.DB_USER }}
+        FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
+      run: |
+        flyway migrate -locations=filesystem:migrations
 
-      - name: Test
-        run: |
-          dbopstest \
-            -test.v \
-            -host=${{ secrets.DB_HOST }} \
-            -port=${{ secrets.DB_PORT }} \
-            -user=${{ secrets.DB_USER }} \
-            -password=${{ secrets.DB_PASSWORD }} \
-            -db=${{ secrets.DB_NAME }}
+    ### Этот шаг оставьте без изменений
+    - name: Download and setup autotests binaries
+      run: |
+        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
+        chmod +x ./dbopstest
+        mv ./dbopstest /usr/local/bin/dbopstest
+
+    ### Этот шаг оставьте без изменений
+    - name: Test
+      run: |
+        dbopstest \
+          -test.v \
+          -host=${{ secrets.DB_HOST }} \
+          -port=${{ secrets.DB_PORT }} \
+          -user=${{ secrets.DB_USER }} \
+          -password=${{ secrets.DB_PASSWORD }} \
+          -db=${{ secrets.DB_NAME }}
